---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oxomine
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "oxomine"
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: oxomine
          servicePort: 80
