---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: oxomine-oxon-ch
  namespace: default
spec:
  secretName: oxomine-oxon-ch-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: oxomine.oxon.ch
  dnsNames:
  - oxomine.oxon.ch
  acme:
    config:
    - http01:
        ingress: oxomine
      domains:
      - oxomine.oxon.ch
