---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: oxomine-stfu-ch
  namespace: default
spec:
  secretName: oxomine-stfu-ch-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: oxomine.stfu.ch
  dnsNames:
  - oxomine.stfu.ch
  acme:
    config:
    - http01:
        ingress: oxomine
      domains:
      - oxomine.stfu.ch
