production:
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV.fetch('S3_BUCKET', 'oxomine-uploads') %>
  endpoint: <%= ENV.fetch('S3_ENDPOINT', 'storage.googleapis.com') %>
